
name: 'mt'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 2 * * 0'

jobs:
  leetcode-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install requests
      - name: 'Working'
        env:
          SCKEY: ${{ secrets.USERNAME }}
                 ${{ secrets.PASSWORD }}
        run: python mt论坛.py

